<?xml version="1.0"?>

<robot name="taurob_tracker" xmlns:xacro="http://www.ros.org/wiki/xacro" >
  
  <xacro:include filename="$(find hector_xacro_tools)/urdf/inertia_tensors.urdf.xacro" />
  
  <xacro:macro name="tracker_chassis_macro">
    <xacro:property name="tracker_base_size_x" value="1.0" />
    <xacro:property name="tracker_base_size_y" value="0.5" />
    <xacro:property name="tracker_base_size_z" value="0.2 " />
  
    <xacro:property name="tracker_base_offset_x" value="-0.122" />
    <xacro:property name="tracker_base_offset_z" value="-0.08" />

    <xacro:property name="flipper_offset_x" value="-0.051" />
    <xacro:property name="flipper_upper_shortening_x" value="0.05" />

    <!-- width overall is 0.58 ->  (0.58 - 0.0925)/2 = 0.24375 -->
    <xacro:property name="track_offset_y" value="0.24375" />
    <!--Below pending clarification-->
    <xacro:property name="track_offset_z" value="-0.09" /> 

    <xacro:property name="track_wheel_radius" value="0.13" />
    <xacro:property name="track_width" value="0.0925" />
   
    <link name="base_link"/>
    
    <joint name="chassis_joint" type="fixed">
      <origin xyz="${-tracker_base_offset_x} 0 0.193" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="chassis_link"/>
    </joint>
    
    <link name="flipper_link_1">
      <xacro:inertial_cuboid_with_pose mass="1.0" x_length="${tracker_base_size_x*0.5}" y_length="${track_width*2}" z_length="0.17651" >
        <origin xyz="${tracker_base_size_x*0.5-track_wheel_radius*2} 0.0 0.0" rpy="0 0 0" />
      </xacro:inertial_cuboid_with_pose>    
      <origin xyz="0 0 0" rpy="0 0 0" />
      
      <visual>
        <origin xyz="${tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x} -${track_offset_y} 0.0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      
      <visual>
        <origin xyz="0 -${track_offset_y} 0.0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      
      <visual>
        <origin xyz="${(tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x)*0.5} -${track_offset_y} 0.0" rpy="0 0 0"/>
        <geometry>
          <box size="${tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x} ${track_width} ${track_wheel_radius*2}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      
      <visual>
        <origin xyz="${tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x} ${track_offset_y} 0.0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      
      <visual>
        <origin xyz="0 ${track_offset_y} 0.0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>      
      
      <visual>
        <origin xyz="${(tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x)*0.5} ${track_offset_y} 0.0" rpy="0 0 0"/>
        <geometry>
          <box size="${tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x} ${track_width} ${track_wheel_radius*2}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      
      
      <collision>
        <origin xyz="${tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x} -${track_offset_y} 0.0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
        </geometry>
      </collision>
      
      <collision>
        <origin xyz="0 -${track_offset_y} 0.0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
        </geometry>
      </collision>
      
      <collision>
        <origin xyz="${(tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x)*0.5} -${track_offset_y} 0.0" rpy="0 0 0"/>
        <geometry>
          <box size="${tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x} ${track_width} ${track_wheel_radius*2}"/>
        </geometry>
      </collision>
      
      <collision>
        <origin xyz="${tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x} ${track_offset_y} 0.0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
        </geometry>
      </collision>
      
      <collision>
        <origin xyz="0 ${track_offset_y} 0.0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
        </geometry>
      </collision>      
      
      <collision>
        <origin xyz="${(tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x)*0.5} ${track_offset_y} 0.0" rpy="0 0 0"/>
        <geometry>
          <box size="${tracker_base_size_x*0.5-track_wheel_radius+flipper_offset_x} ${track_width} ${track_wheel_radius*2}"/>
        </geometry>
      </collision>    
    </link>    
    
    
    <joint name="flipper_joint" type="revolute">
      <origin xyz="${tracker_base_offset_x-flipper_offset_x} 0 ${track_offset_z}" rpy="0 0 0" />
      <axis xyz="0 1 0"/>
      
      <limit lower="${-50 * pi / 180}" upper="${30 * pi / 180}"
             effort="10000" velocity="${1.0 * 30 * pi / 180}" />
<!--      <safety_controller soft_lower_limit="${-25 * pi / 180}"
                         soft_upper_limit="${45 * pi / 180}"
                         k_position="${100}"
                         k_velocity="${2}"/>-->
      
      <parent link="chassis_link"/>
      <child link="flipper_link_1"/>
    </joint>
    
    
    <link name="chassis_link">
      
      <xacro:inertial_cuboid_with_pose mass="30" x_length="${tracker_base_size_x*0.66}" y_length="${tracker_base_size_y}" z_length="${tracker_base_size_z}" >
        <origin xyz="${-tracker_base_size_x*0.25} 0.0 -0.05" rpy="0 0 0" />
      </xacro:inertial_cuboid_with_pose>
      
      <!--Primitives with materials need to be used before .dae, otherwise material does not get applied-->
      
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://taurob_agx_bringup/meshes/tracker_chassis_no_tracks.dae"/>
        </geometry>
      </visual>
      
      <!--Chassis middle-->
      <collision>
        <origin xyz="${tracker_base_offset_x-0.13} 0.0 ${tracker_base_offset_z+0.005}" rpy="0 0 0"/>
        <geometry>
          <box size="0.7 0.5 0.15"/>
        </geometry>
      </collision>
      
    </link>
    
  </xacro:macro>
  
</robot>
