controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - flipper_joint
      - arm_joint_0
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
    frame_id:
      - arm_link_0

joint_trajectory_controller:
  ros__parameters:
    joints:
      - flipper_joint
      - arm_joint_0
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false

    gains:
      arm_joint_0: { p: 0.5, d: 0.2, i: 0.0, i_clamp: 0.5, ff_velocity_scale: 1. }
      arm_joint_1: { p: 0.5, d: 0.2, i: 0.0, i_clamp: 0.5, ff_velocity_scale: 1. }
      arm_joint_2: { p: 0.5, d: 0.2, i: 0.0, i_clamp: 0.5, ff_velocity_scale: 1. }
      arm_joint_3: { p: 0.5, d: 0.2, i: 0.0, i_clamp: 0.5, ff_velocity_scale: 1. }
      flipper_joint: { p: 0.5, d: 0.2, i: 0.0, i_clamp: 0.5, ff_velocity_scale: 1. }

