controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - flipper_joint
      - arm_joint_0
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - left_wheel_joint
      - right_wheel_joint
    frame_id:
      - arm_link_0

joint_trajectory_controller:
  ros__parameters:
    joints:
      - flipper_joint
      - arm_joint_0
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false

    gains:
      arm_joint_0: { p: 0.5, d: 0.2, i: 0.0, i_clamp: 0.5, ff_velocity_scale: 1. }
      arm_joint_1: { p: 0.5, d: 0.2, i: 0.0, i_clamp: 0.5, ff_velocity_scale: 1. }
      arm_joint_2: { p: 0.5, d: 0.2, i: 0.0, i_clamp: 0.5, ff_velocity_scale: 1. }
      arm_joint_3: { p: 0.5, d: 0.2, i: 0.0, i_clamp: 0.5, ff_velocity_scale: 1. }
      flipper_joint: { p: 0.5, d: 0.2, i: 0.0, i_clamp: 0.5, ff_velocity_scale: 1. }

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.58
    wheel_radius: 0.0925

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10
